### ISSUE TITLE
Error linking iron_c library on Windows.

### ISSUE THREAD

**Issue by hsorby** [OpenCMISS/iron#119]
Building with Windows using Visual Studio 14 2015 Win64 the iron_c library failed to link with the following missing symbols::

```
CMFE_FIELD_GEOMETRICPARAMETERSELEMENTVOLUMEGETNUMBER
CMFE_FIELD_GEOMETRICPARAMETERSELEMENTVOLUMEGETOBJ
```

**Comment by chrispbradley** [comment]
Fixed by https://github.com/OpenCMISS/iron/pull/120
