### ISSUE TITLE
Cantilever keytests not converging.

### ISSUE THREAD

**Issue by hsorby** [OpenCMISS/iron#125]
The Cantilever test is no longer converging and causing an MPI_ABORT to occur.  This can be seen in both Fortran and Python Cantilever keytests.

**Comment by chrispbradley** [comment]
By Cantilever keytests do you mean https://github.com/OpenCMISS-Examples/cantilever or https://github.com/OpenCMISS/iron/blob/develop/tests/FiniteElasticity/Cantilever.f90? I assume the former as there is no python with the later? I've just built the current develop branch of https://github.com/OpenCMISS/iron and the develop branch of https://github.com/OpenCMISS-Examples/cantilever works fine on Linux? What configuration?

**Comment by hsorby** [comment]
No, I do mean the tests that are part of iron
[FiniteElasticity_Cantilever](https://github.com/OpenCMISS/iron/blob/develop/tests/FiniteElasticity/Cantilever.f90).

This is used as one of the keytests.  It fails on the PAN cluster and on macOS running under a release configuration.  These tests have only recently started failing.

**Comment by hsorby** [comment]
PR #126 does fix this problem for macOS.

**Comment by hsorby** [comment]
Fixed with the merge of PR #126.
